services:
  app:
    restart: unless-stopped
    environment:
      OM_INIT_SUPERADMIN_EMAIL: ${OM_INIT_SUPERADMIN_EMAIL:-}
      OM_INIT_SUPERADMIN_PASSWORD: ${FINOO_BOOTSTRAP_SUPERADMIN_PASSWORD:-}
      OM_INIT_ADMIN_EMAIL: ${OM_INIT_ADMIN_EMAIL:-}
      OM_INIT_ADMIN_PASSWORD: ${FINOO_BOOTSTRAP_ADMIN_PASSWORD:-}
      OM_INIT_EMPLOYEE_EMAIL: ${OM_INIT_EMPLOYEE_EMAIL:-}
      OM_INIT_EMPLOYEE_PASSWORD: ${FINOO_BOOTSTRAP_EMPLOYEE_PASSWORD:-}
      OM_INIT_REDACT_CREDENTIAL_OUTPUT: "true"
      MERCATO_INIT_ARGS: ${MERCATO_INIT_ARGS:---no-examples}
  redis:
    restart: unless-stopped
